spring.application.name=Taskzen

spring.datasource.url=jdbc:postgresql://localhost:5432/taskzen
spring.datasource.username=postgres
spring.datasource.password=Welcome#31
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true